{% set name = "pyTMD" %}
{% set version = "2.2.9.1" %}
{% set sha256 = "51a56073b341ec2c5c08c7127d2ae178f740360c1725f15212d1ba6aba16ff99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - fetch_arcticdata.py = pyTMD.datasets.fetch_arcticdata:main
    - fetch_aviso_fes.py = pyTMD.datasets.fetch_aviso_fes:main
    - fetch_gsfc_got.py = pyTMD.datasets.fetch_gsfc_got:main
    - fetch_test_data.py = pyTMD.datasets.fetch_test_data:main
    - reduce_otis.py = pyTMD.datasets.reduce_otis:main
    - verify_box_tpxo.py = pyTMD.datasets.verify_box_tpxo:main
    - arcticdata_tides.py = pyTMD.datasets.fetch_arcticdata:main
    - aviso_fes_tides.py = pyTMD.datasets.fetch_aviso_fes:main
    - gsfc_got_tides.py = pyTMD.datasets.fetch_gsfc_got:main
    - reduce_OTIS_files.py = pyTMD.datasets.reduce_otis:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
  run:
    - cartopy
    - ipyleaflet
    - ipywidgets
    - jplephem
    - jupyterlab
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - platformdirs
    - pyproj >=2.5.0
    - python >={{ python_min }}
    - python-dateutil
    - pyyaml
    - scipy >=1.10.1
    - setuptools
    - timescale >=0.0.8
    - xarray

test:
  imports:
    - pyTMD
  commands:
    - pip check
    - fetch_arcticdata.py --help
    - fetch_aviso_fes.py --help
    - fetch_gsfc_got.py --help
    - fetch_test_data.py --help
    - reduce_otis.py --help
    - verify_box_tpxo.py --help
    - arcticdata_tides.py --help
    - aviso_fes_tides.py --help
    - gsfc_got_tides.py --help
    - reduce_OTIS_files.py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/pyTMD
  summary: Python-based tidal prediction software
  license: MIT
  license_file: LICENSE
  description: |
    Python-based tidal prediction software for estimating ocean, load, solid Earth and pole tides
  doc_url: https://pytmd.readthedocs.io/
  dev_url: https://github.com/pyTMD/pyTMD

extra:
  recipe-maintainers:
    - tsutterley
    - mrsiegfried
