{% set name = "pyTMD" %}
{% set version = "1.1.3" %}
{% set sha256 = "30a4d280df8c83be196b4cdeb6fd9a35a5b9c15c20076dcb69176bc5d19302fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools
  run:
    - gdal
    - h5py
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pyproj
    - python >=3.6
    - python-dateutil
    - pyyaml
    - scipy
    - setuptools-scm
    - setuptools

test:
  imports:
    - pyTMD
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tsutterley/pyTMD
  summary: Tide Model Driver to read OTIS, GOT and FES formatted tidal solutions and make tidal predictions
  license: MIT
  license_file: LICENSE
  description: |
    Python-based tidal prediction software that reads OTIS, GOT and FES formatted
    tidal solutions for predicting ocean and load tides and can use IERS conventions
    for calculating radial pole tide displacements
  doc_url: https://pytmd.readthedocs.io/
  dev_url: https://github.com/tsutterley/pyTMD

extra:
  recipe-maintainers:
    - tsutterley
    - mrsiegfried
