{% set name = "pyTMD" %}
{% set version = "2.2.9" %}
{% set sha256 = "e498a10c3cda21521eef3b2c3c2c7b128fdb93c071ed07f1a2b8ea13da8aaf65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cartopy
    - ipyleaflet
    - ipywidgets
    - jplephem
    - jupyterlab
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - platformdirs
    - pyproj
    - python >={{ python_min }}
    - python-dateutil
    - pyyaml
    - scipy >=1.10.1
    - setuptools
    - timescale >=0.0.8
    - xarray

test:
  imports:
    - pyTMD
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/pyTMD
  summary: Python-based tidal prediction software
  license: MIT
  license_file: LICENSE
  description: |
    Python-based tidal prediction software for estimating ocean, load, solid Earth and pole tides
  doc_url: https://pytmd.readthedocs.io/
  dev_url: https://github.com/pyTMD/pyTMD

extra:
  recipe-maintainers:
    - tsutterley
    - mrsiegfried
