{% set name = "pyTMD" %}
{% set version = "3.0.0" %}
{% set sha256 = "53e1f15a0d27c398514805c274473dc89ccee383f1de1bba46c0376cca308c27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cartopy
    - dask
    - h5netcdf
    - ipyleaflet
    - ipywidgets
    - jplephem
    - jupyterlab
    - lxml
    - matplotlib-base
    - numpy
    - obstore
    - pandas
    - pint
    - platformdirs
    - pyarrow
    - pyproj >=2.5.0
    - python >={{ python_min }}
    - pyyaml
    - s3fs
    - scipy >=1.10.1
    - setuptools
    - timescale >=0.0.8
    - xarray
    - zarr

test:
  imports:
    - pyTMD
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/pyTMD
  summary: Python-based tidal prediction software
  license: MIT
  license_file: LICENSE
  description: |
    Python-based tidal prediction software for estimating ocean, load, solid Earth and pole tides
  doc_url: https://pytmd.readthedocs.io/
  dev_url: https://github.com/pyTMD/pyTMD

extra:
  recipe-maintainers:
    - tsutterley
    - mrsiegfried
