context:
  name: "pyTMD"
  version: "3.0.1"
  sha256: "406dd374ea01e5eaadd0d504d55cbe074103705304ce7b4b69d273750af52be3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  noarch: python
  script:
    - python -m pip install . -vv
  number: 0
  entry_points:
    - fetch_arcticdata.py = pyTMD.datasets.fetch_arcticdata:main
    - fetch_aviso_fes.py = pyTMD.datasets.fetch_aviso_fes:main
    - fetch_gsfc_got.py = pyTMD.datasets.fetch_gsfc_got:main
    - fetch_iers_opole.py = pyTMD.datasets.fetch_iers_opole:main
    - fetch_jpl_ssd.py = pyTMD.datasets.fetch_jpl_ssd:main
    - fetch_test_data.py = pyTMD.datasets.fetch_test_data:main
    - reduce_otis.py = pyTMD.datasets.reduce_otis:main

requirements:
  host:
    - python >=3.9,<4.dev0
    - setuptools >=64
    - pip
  run:
    - python >=3.9
    - cartopy
    - dask
    - h5netcdf
    - ipyleaflet
    - ipywidgets
    - jplephem
    - jupyterlab
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - pint
    - platformdirs
    - pyproj >=2.5.0
    - scipy >=1.10.1
    - timescale >=0.0.8
    - xarray

test:
  imports:
    - pyTMD
  commands:
    - pip check
    - fetch_arcticdata.py --help
    - fetch_aviso_fes.py --help
    - fetch_gsfc_got.py --help
    - fetch_iers_opole.py --help
    - fetch_jpl_ssd.py --help
    - fetch_test_data.py --help
    - reduce_otis.py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/pyTMD
  summary: Python-based tidal prediction software
  license: MIT
  license_file: LICENSE
  description: |
    Python-based tidal prediction software for estimating ocean, load, 
    solid Earth and pole tides
  documentation: https://pytmd.readthedocs.io/
  repository: https://github.com/pyTMD/pyTMD

extra:
  recipe-maintainers:
    - tsutterley
    - mrsiegfried
